\chapter{p-\/retry}
\hypertarget{md_node__modules_2p-retry_2readme}{}\label{md_node__modules_2p-retry_2readme}\index{p-\/retry@{p-\/retry}}
\label{md_node__modules_2p-retry_2readme_autotoc_md20249}%
\Hypertarget{md_node__modules_2p-retry_2readme_autotoc_md20249}%
 \begin{quote}
Retry a promise-\/returning or async function \end{quote}
It does exponential backoff and supports custom retry strategies for failed operations.\hypertarget{md_node__modules_2p-retry_2readme_autotoc_md20250}{}\doxysection{\texorpdfstring{Install}{Install}}\label{md_node__modules_2p-retry_2readme_autotoc_md20250}

\begin{DoxyCode}{0}
\DoxyCodeLine{\$\ npm\ install\ p-\/retry}

\end{DoxyCode}
\hypertarget{md_node__modules_2p-retry_2readme_autotoc_md20251}{}\doxysection{\texorpdfstring{Usage}{Usage}}\label{md_node__modules_2p-retry_2readme_autotoc_md20251}

\begin{DoxyCode}{0}
\DoxyCodeLine{const\ pRetry\ =\ require('p-\/retry');}
\DoxyCodeLine{const\ fetch\ =\ require('node-\/fetch');}
\DoxyCodeLine{}
\DoxyCodeLine{const\ run\ =\ async\ ()\ =>\ \{}
\DoxyCodeLine{\ \ \ \ const\ response\ =\ await\ fetch('https://sindresorhus.com/unicorn');}
\DoxyCodeLine{}
\DoxyCodeLine{\ \ \ \ //\ Abort\ retrying\ if\ the\ resource\ doesn't\ exist}
\DoxyCodeLine{\ \ \ \ if\ (response.status\ ===\ 404)\ \{}
\DoxyCodeLine{\ \ \ \ \ \ \ \ throw\ new\ pRetry.AbortError(response.statusText);}
\DoxyCodeLine{\ \ \ \ \}}
\DoxyCodeLine{}
\DoxyCodeLine{\ \ \ \ return\ response.blob();}
\DoxyCodeLine{\};}
\DoxyCodeLine{}
\DoxyCodeLine{(async\ ()\ =>\ \{}
\DoxyCodeLine{\ \ \ \ console.log(await\ pRetry(run,\ \{retries:\ 5\}));}
\DoxyCodeLine{\})();}

\end{DoxyCode}
\hypertarget{md_node__modules_2p-retry_2readme_autotoc_md20252}{}\doxysection{\texorpdfstring{API}{API}}\label{md_node__modules_2p-retry_2readme_autotoc_md20252}
\hypertarget{md_node__modules_2p-retry_2readme_autotoc_md20253}{}\doxysubsection{\texorpdfstring{p\+Retry(input, options?)}{pRetry(input, options?)}}\label{md_node__modules_2p-retry_2readme_autotoc_md20253}
Returns a {\ttfamily Promise} that is fulfilled when calling {\ttfamily input} returns a fulfilled promise. If calling {\ttfamily input} returns a rejected promise, {\ttfamily input} is called again until the maximum number of retries is reached. It then rejects with the last rejection reason.

Does not retry on most {\ttfamily Type\+Errors}, with the exception of network errors. This is done on a best case basis as different browsers have different \href{https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch\#Checking_that_the_fetch_was_successful}{\texttt{ messages}} to indicate this. See \href{https://github.com/whatwg/fetch/issues/526\#issuecomment-554604080}{\texttt{ whatwg/fetch\#526 (comment)}}\hypertarget{md_node__modules_2p-retry_2readme_autotoc_md20254}{}\doxysubsubsection{\texorpdfstring{input}{input}}\label{md_node__modules_2p-retry_2readme_autotoc_md20254}
Type\+: {\ttfamily Function}

Receives the current attempt number as the first argument and is expected to return a {\ttfamily Promise} or any value.\hypertarget{md_node__modules_2p-retry_2readme_autotoc_md20255}{}\doxysubsubsection{\texorpdfstring{options}{options}}\label{md_node__modules_2p-retry_2readme_autotoc_md20255}
Type\+: {\ttfamily object}

Options are passed to the \href{https://github.com/tim-kos/node-retry\#retryoperationoptions}{\texttt{ {\ttfamily retry}}} module.\hypertarget{md_node__modules_2p-retry_2readme_autotoc_md20256}{}\doxyparagraph{\texorpdfstring{on\+Failed\+Attempt(error)}{onFailedAttempt(error)}}\label{md_node__modules_2p-retry_2readme_autotoc_md20256}
Type\+: {\ttfamily Function}

Callback invoked on each retry. Receives the error thrown by {\ttfamily input} as the first argument with properties {\ttfamily attempt\+Number} and {\ttfamily retries\+Left} which indicate the current attempt number and the number of attempts left, respectively.


\begin{DoxyCode}{0}
\DoxyCodeLine{const\ run\ =\ async\ ()\ =>\ \{}
\DoxyCodeLine{\ \ \ \ const\ response\ =\ await\ fetch('https://sindresorhus.com/unicorn');}
\DoxyCodeLine{}
\DoxyCodeLine{\ \ \ \ if\ (!response.ok)\ \{}
\DoxyCodeLine{\ \ \ \ \ \ \ \ throw\ new\ Error(response.statusText);}
\DoxyCodeLine{\ \ \ \ \}}
\DoxyCodeLine{}
\DoxyCodeLine{\ \ \ \ return\ response.json();}
\DoxyCodeLine{\};}
\DoxyCodeLine{}
\DoxyCodeLine{(async\ ()\ =>\ \{}
\DoxyCodeLine{\ \ \ \ const\ result\ =\ await\ pRetry(run,\ \{}
\DoxyCodeLine{\ \ \ \ \ \ \ \ onFailedAttempt:\ error\ =>\ \{}
\DoxyCodeLine{\ \ \ \ \ \ \ \ \ \ \ \ console.log(`Attempt\ \$\{error.attemptNumber\}\ failed.\ There\ are\ \$\{error.retriesLeft\}\ retries\ left.`);}
\DoxyCodeLine{\ \ \ \ \ \ \ \ \ \ \ \ //\ 1st\ request\ =>\ Attempt\ 1\ failed.\ There\ are\ 4\ retries\ left.}
\DoxyCodeLine{\ \ \ \ \ \ \ \ \ \ \ \ //\ 2nd\ request\ =>\ Attempt\ 2\ failed.\ There\ are\ 3\ retries\ left.}
\DoxyCodeLine{\ \ \ \ \ \ \ \ \ \ \ \ //\ â€¦}
\DoxyCodeLine{\ \ \ \ \ \ \ \ \},}
\DoxyCodeLine{\ \ \ \ \ \ \ \ retries:\ 5}
\DoxyCodeLine{\ \ \ \ \});}
\DoxyCodeLine{}
\DoxyCodeLine{\ \ \ \ console.log(result);}
\DoxyCodeLine{\})();}

\end{DoxyCode}


The {\ttfamily on\+Failed\+Attempt} function can return a promise. For example, you can do some async logging\+:


\begin{DoxyCode}{0}
\DoxyCodeLine{const\ pRetry\ =\ require('p-\/retry');}
\DoxyCodeLine{const\ logger\ =\ require('./some-\/logger');}
\DoxyCodeLine{}
\DoxyCodeLine{const\ run\ =\ async\ ()\ =>\ \{\ â€¦\ \};}
\DoxyCodeLine{}
\DoxyCodeLine{(async\ ()\ =>\ \{}
\DoxyCodeLine{\ \ \ \ const\ result\ =\ await\ pRetry(run,\ \{}
\DoxyCodeLine{\ \ \ \ \ \ \ \ onFailedAttempt:\ async\ error\ =>\ \{}
\DoxyCodeLine{\ \ \ \ \ \ \ \ \ \ \ \ await\ logger.log(error);}
\DoxyCodeLine{\ \ \ \ \ \ \ \ \}}
\DoxyCodeLine{\ \ \ \ \});}
\DoxyCodeLine{\})();}

\end{DoxyCode}


If the {\ttfamily on\+Failed\+Attempt} function throws, all retries will be aborted and the original promise will reject with the thrown error.\hypertarget{md_node__modules_2p-retry_2readme_autotoc_md20257}{}\doxysubsection{\texorpdfstring{p\+Retry.\+Abort\+Error(message)}{pRetry.AbortError(message)}}\label{md_node__modules_2p-retry_2readme_autotoc_md20257}
\hypertarget{md_node__modules_2p-retry_2readme_autotoc_md20258}{}\doxysubsection{\texorpdfstring{p\+Retry.\+Abort\+Error(error)}{pRetry.AbortError(error)}}\label{md_node__modules_2p-retry_2readme_autotoc_md20258}
Abort retrying and reject the promise.\hypertarget{md_node__modules_2p-retry_2readme_autotoc_md20259}{}\doxysubsection{\texorpdfstring{message}{message}}\label{md_node__modules_2p-retry_2readme_autotoc_md20259}
Type\+: {\ttfamily string}

Error message.\hypertarget{md_node__modules_2p-retry_2readme_autotoc_md20260}{}\doxysubsection{\texorpdfstring{error}{error}}\label{md_node__modules_2p-retry_2readme_autotoc_md20260}
Type\+: {\ttfamily Error}

Custom error.\hypertarget{md_node__modules_2p-retry_2readme_autotoc_md20261}{}\doxysection{\texorpdfstring{Tip}{Tip}}\label{md_node__modules_2p-retry_2readme_autotoc_md20261}
You can pass arguments to the function being retried by wrapping it in an inline arrow function\+:


\begin{DoxyCode}{0}
\DoxyCodeLine{const\ pRetry\ =\ require('p-\/retry');}
\DoxyCodeLine{}
\DoxyCodeLine{const\ run\ =\ async\ emoji\ =>\ \{}
\DoxyCodeLine{\ \ \ \ //\ â€¦}
\DoxyCodeLine{\};}
\DoxyCodeLine{}
\DoxyCodeLine{(async\ ()\ =>\ \{}
\DoxyCodeLine{\ \ \ \ //\ Without\ arguments}
\DoxyCodeLine{\ \ \ \ await\ pRetry(run,\ \{retries:\ 5\});}
\DoxyCodeLine{}
\DoxyCodeLine{\ \ \ \ //\ With\ arguments}
\DoxyCodeLine{\ \ \ \ await\ pRetry(()\ =>\ run('ðŸ¦„'),\ \{retries:\ 5\});}
\DoxyCodeLine{\})();}

\end{DoxyCode}
\hypertarget{md_node__modules_2p-retry_2readme_autotoc_md20262}{}\doxysection{\texorpdfstring{Related}{Related}}\label{md_node__modules_2p-retry_2readme_autotoc_md20262}

\begin{DoxyItemize}
\item \href{https://github.com/sindresorhus/p-timeout}{\texttt{ p-\/timeout}} -\/ Timeout a promise after a specified amount of time
\item \href{https://github.com/sindresorhus/promise-fun}{\texttt{ Moreâ€¦}} 
\end{DoxyItemize}